const AmhObject = {
  marketPlace: "ገበያ",
  hireCreator: "ቅጠር",
  upload: "ለጥፍ",
  uploadYourWork: "ስራህን ለጥፍ",
  dragNDrop: "ፎቶዎችን ወደዚህ ሳብ ወይም ምረጥ",
  recommendedSize: "1600X1200 ወይም ተጨማሪ ሪዞሊውሽን ይመከራል። ቢበዛ 10ሜባ",
  exploreThrough: "ዓለም አቀፍ እና ሀገር",
  ourDiverse: "አቀፍ ምስል",
  content: "ይከታተሉ።",
  searchContent: "ፎቶዎች ፈልግ",
  searchCreator: "ሰሪዎችን ፈልግ",
  startExploring: "መፈለግ ጀምር",
  viewNotification: "መልዕክቶችን ተመልከት",
  moderator: "ተቆጣጣሪ",
  profile: "የግል መረጃ",
  dashboard: "መቆጣጠሪያ",
  jobs: "ስራዎች",
  chat: "የግል መልዕክቶች",
  signout: "ውጣ",
  wallet: "ዋሌት",
  onlyYour: "ባለቤት የሆኑበትን ምስል ብቻ ይለጥፉ።",
  continue: "ቀጥል",
  description: "መግለጫ",
  title: "ርዕስ",
  tags: "መለያ",
  price: "ዋጋ",
  revenuePerDay: "የቀን ገቢ",
  revenueDistribution: "የገቢ ክፍፍል",
  editProfile: "መረጃ አድስ",
  likesPerDay: "በቀን የተወደዱ",
  viewsPerDay: "በቀን የታዩ",
  viewProfile: "መረጃ ተመልከት",
  highestGrossing: "ብዙ ገቢ ያስገባ",
  mostLiked: "ብዙ የተወደደ",
  mostViewed: "ብዙ የታየ",
  creators: "አንሺዎችን ይፈልጉ።"
}

export default AmhObject
