const EngObject = {
  marketPlace: "MarketPlace",
  hireCreator: "Hire Creator",
  upload: "Upload",
  uploadYourWork: "Upload Your Work",
  dragNDrop: "Drag and Drop Content, or Click to Browse Image",
  recommendedSize: "1600X1200 or higher resolutions recommended. Max 10MB",
  exploreThrough: "Explore Through",
  ourDiverse: "our Diverse",
  content: "Content.",
  searchContent: "Search Contents",
  searchCreator: "Search Creators",
  startExploring: "Start Exploring",
  viewNotification: "View Notifications",
  moderator: "Moderator",
  profile: "Profile",
  dashboard: "Dashboard",
  jobs: "Jobs",
  chat: "Chat",
  signout: "Sign Out",
  wallet: "Wallet",
  onlyYour: "Only Upload Media You Own the Rights to.",
  continue: "Continue",
  description: "Description",
  title: "Title",
  tags: "Tags",
  price: "Price",
  revenuePerDay: "Revenue Per Day",
  revenueDistribution: "Revenue Distribution",
  editProfile: "Edit Profile",
  likesPerDay: "Likes Per Day",
  viewsPerDay: "Views Per Day",
  viewProfile: "View Profile",
  highestGrossing: "Highest Grossing",
  mostLiked: "Most Liked",
  mostViewed: "Most Viewed"

}

export default EngObject
